# Removed version as it's obsolete in current Docker Compose

services:
  azubi-foerderung:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:8080"
    container_name: azubi-foerderung-web
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Environment variables
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=8080
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    
    # Security options
    security_opt:
      - no-new-privileges:true

  # Optional: Add a reverse proxy for production (commented out for local development)
  # nginx-proxy:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./proxy.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - azubi-foerderung
  #   restart: unless-stopped

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

# Optional: Volumes for persistent data (if needed in the future)
# volumes:
#   nginx_cache:
#     driver: local
